-- Start
hl.on("hyprland.start", function()
  hl.dispatch(hl.dsp.focus({ workspace = "2" }))
  hl.exec_cmd("__hypr_tmux_sessions")
  hl.exec_cmd("systemctl --user enable --now hyprpolkitagent.service")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("uwsm app -s a -- swaync")
  hl.exec_cmd("uwsm app -s b -- hypridle")
  hl.exec_cmd("uwsm app -s b -- Thunar --daemon")
  hl.exec_cmd("uwsm app -- kitty --hold __tmuxinator_sessions", { workspace = "special:term silent" })
  hl.exec_cmd("uwsm app -s a -- firefox-default.desktop", { workspace = "2" })
  StartWaybar(Monitors.laptop.name)
end)

-- Monitors
hl.on("monitor.added", function()
  Func.reload_layout()
end)

hl.on("monitor.removed", function()
  Func.reload_layout()
end)

hl.bind("switch:on:Lid Switch", function()
  hl.monitor({ output = "eDP-1", disabled = true })
  Func.reload_layout()
end)

hl.bind("switch:off:Lid Switch", function()
  hl.monitor({ output = "eDP-1", disabled = false })
  Func.reload_layout()
end)

-- Windows
hl.on("window.open", function()
  DynamicLayout()
end)
hl.on("window.destroy", function()
  DynamicLayout()
end)
hl.on("window.move_to_workspace", function()
  DynamicLayout()
end)
hl.on("window.fullscreen", function()
  DynamicLayout()
end)
